import AppKit
import Combine

struct ClipItem: Identifiable, Equatable {
    let id = UUID()
    let text: String
    let date: Date

    var preview: String {
        let collapsed = text
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "  ", with: " ")
        return collapsed.count > 90 ? String(collapsed.prefix(89)) + "…" : collapsed
    }

    var lineCount: Int { text.split(separator: "\n").count }
}

/// Clipboard history, held in memory only.
///
/// Two deliberate limits: entries marked concealed (what password managers set) are
/// never recorded, and history is capped. It's also never written to disk — a plaintext
/// file of everything you've ever copied is a liability, so history clears on quit.
final class ClipboardStore: ObservableObject {
    @Published private(set) var items: [ClipItem] = []

    static let limit = 50

    /// Password managers mark their pasteboard entries with these so history tools skip
    /// them; transient entries are explicitly "don't store this" as well.
    private static let excludedTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    func start() {
        guard timer == nil else { return }
        // The pasteboard has no change notification, so polling is the only option.
        timer = Timer.scheduledTimer(withTimeInterval: 0.6, repeats: true) { [weak self] _ in
            self?.poll()
        }
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.excludedTypes) else { return }

        guard let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        guard items.first?.text != text else { return }

        // Re-copying something old moves it back to the top rather than duplicating.
        items.removeAll { $0.text == text }
        items.insert(ClipItem(text: text, date: Date()), at: 0)
        if items.count > Self.limit {
            items.removeLast(items.count - Self.limit)
        }
    }

    func copy(_ item: ClipItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(item.text, forType: .string)
        // Our own write shouldn't come back around as a new entry.
        lastChangeCount = pasteboard.changeCount
        if let index = items.firstIndex(of: item), index != 0 {
            items.remove(at: index)
            items.insert(item, at: 0)
        }
    }

    func remove(_ item: ClipItem) {
        items.removeAll { $0.id == item.id }
    }

    func clear() {
        items.removeAll()
    }
}
